In [1]:
import torch

In [18]:
x = torch.ones(5)
y = torch.zeros(3)

w = torch.randn(5, 3, requires_grad=True)
print(w)
b = torch.randn(3, requires_grad=True)
print(b)

z = torch.matmul(x, w) + b

tensor([[-0.5335,  0.0791, -0.5357],
        [ 0.0264,  0.3947,  1.4179],
        [-0.2464, -0.5490, -0.9981],
        [ 0.0278,  0.1271,  0.2995],
        [ 0.4818,  0.6688,  0.8232]], requires_grad=True)
tensor([-0.2859, -1.3410,  1.2323], requires_grad=True)


In [19]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss

tensor(1.0779, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)

In [20]:
print(f'Gradient function for z = {z.grad_fn}')
print(f'Gradient function for loss = {loss.grad_fn}')

Gradient function for z = <AddBackward0 object at 0x10ffd5fd0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward object at 0x10ffd56a0>


In [21]:
print(w.grad)
print(b.grad)
loss.backward()
print(w.grad)
print(b.grad)

None
None
tensor([[0.1235, 0.1166, 0.3012],
        [0.1235, 0.1166, 0.3012],
        [0.1235, 0.1166, 0.3012],
        [0.1235, 0.1166, 0.3012],
        [0.1235, 0.1166, 0.3012]])
tensor([0.1235, 0.1166, 0.3012])


In [26]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():             # Alternatively use detach
    z = torch.matmul(x, w) + b
print(z.requires_grad)

z = torch.matmul(x, w) + b
print(z.requires_grad)

z_det = z.detach()
print(z_det.requires_grad)

True
False
True
False


In [27]:
inp = torch.eye(5, requires_grad=True)
out = (inp + 1).pow(2)

out.backward(torch.ones_like(inp), retain_graph=True)
print(f'First call\n{inp.grad}')
out.backward(torch.ones_like(inp), retain_graph=True)
print(f'Second call\n{inp.grad}')
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print(f'Call after zeroing gradients\n{inp.grad}')

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])
Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
