In [1]:
import os
import torch
from torch import nn 
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [4]:
class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )
    
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)

        return logits

In [5]:
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [10]:
X = torch.rand(1,28, 28)
print(X.shape)
logits = model(X)
print(logits)
pred_prob = nn.Softmax(dim=1)(logits)
print(pred_prob)
y_pred = pred_prob.argmax(1)
print(f'Predicted class: {y_pred}')

torch.Size([1, 28, 28])
tensor([[ 0.0694,  0.0042,  0.1082, -0.0677, -0.0352, -0.0113, -0.0386, -0.0036,
         -0.0873, -0.0226]], grad_fn=<AddmmBackward>)
tensor([[0.1079, 0.1011, 0.1122, 0.0941, 0.0972, 0.0996, 0.0969, 0.1003, 0.0923,
         0.0984]], grad_fn=<SoftmaxBackward>)
Predicted class: tensor([2])


In [11]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [12]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [15]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [17]:
print(f'Before ReLU: {hidden1}\n')
hidden_out = nn.ReLU()(hidden1)
print(f'After ReLU: {hidden_out}\n')
hidden_out = nn.ReLU6()(hidden1)
print(f'After ReLU6: {hidden_out}\n')
hidden_out = nn.LeakyReLU()(hidden1)
print(f'After LeakyReLU: {hidden_out}')

Before ReLU: tensor([[-0.2044, -0.0592,  0.5200,  0.1253,  0.2341,  0.5041, -0.4535, -0.3220,
          0.1149, -0.5285, -0.1855, -0.1423,  0.2543,  0.1757, -0.2570,  0.5648,
         -0.4954,  0.0042, -0.0718,  0.2717],
        [-0.2591, -0.2130,  0.7785, -0.4038,  0.4218,  0.3425, -1.1437,  0.0250,
          0.4965, -0.1906, -0.2268, -0.2826,  0.2077, -0.2342, -0.4005,  0.3342,
         -0.3339,  0.3067, -0.0651,  0.3390],
        [-0.1774,  0.0785,  0.6265, -0.4300,  0.0962,  0.2121, -0.5313,  0.0458,
          0.5684, -0.0931, -0.5756, -0.3612,  0.5708, -0.1909, -0.3055, -0.1124,
         -0.5680,  0.3869, -0.0763,  0.1190]], grad_fn=<AddmmBackward>)

After ReLU: tensor([[0.0000, 0.0000, 0.5200, 0.1253, 0.2341, 0.5041, 0.0000, 0.0000, 0.1149,
         0.0000, 0.0000, 0.0000, 0.2543, 0.1757, 0.0000, 0.5648, 0.0000, 0.0042,
         0.0000, 0.2717],
        [0.0000, 0.0000, 0.7785, 0.0000, 0.4218, 0.3425, 0.0000, 0.0250, 0.4965,
         0.0000, 0.0000, 0.0000, 0.2077, 0.0000, 0.0000

In [18]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20,10)
)

In [20]:
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

print(logits)

softmax = nn.Softmax(dim=1)
pred_prob = softmax(logits)

print(pred_prob)

tensor([[-0.1741, -0.0516,  0.1427, -0.0261, -0.2290,  0.0553,  0.0918, -0.0583,
          0.0205, -0.0463],
        [-0.1658, -0.0349,  0.0799, -0.0138, -0.3314,  0.0077,  0.1389, -0.1149,
         -0.0530, -0.0727],
        [-0.2769, -0.1057,  0.0334,  0.1480, -0.2709, -0.0546,  0.1290, -0.1233,
          0.0869, -0.0398]], grad_fn=<AddmmBackward>)
tensor([[0.0859, 0.0971, 0.1179, 0.0996, 0.0813, 0.1080, 0.1120, 0.0964, 0.1043,
         0.0976],
        [0.0889, 0.1014, 0.1137, 0.1035, 0.0754, 0.1058, 0.1206, 0.0936, 0.0996,
         0.0976],
        [0.0787, 0.0934, 0.1073, 0.1204, 0.0792, 0.0983, 0.1181, 0.0918, 0.1132,
         0.0997]], grad_fn=<SoftmaxBackward>)


In [21]:
print(f'Model Structure: {model}\n\n')

for name, param in model.named_parameters():
    print(f'Layer: {name} | Size: {param.size()} | Values: {param[:2]}\n')

Model Structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values: tensor([[-0.0321, -0.0022,  0.0301,  ..., -0.0270,  0.0230, -0.0076],
        [-0.0117,  0.0334, -0.0342,  ...,  0.0263, -0.0167, -0.0116]],
       grad_fn=<SliceBackward>)

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values: tensor([-0.0151, -0.0112], grad_fn=<SliceBackward>)

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values: tensor([[ 0.0021,  0.0005,  0.0136,  ...,  0.0330,  0.0398, -0.0168],
        [ 0.0404, -0.0070,  0.0189,  ..., -0.0254,  0.0198,  0.0092]],
       grad_fn=<SliceBackward>)

Layer: linear_relu_stack.2.bias | Size: tor